In [8]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


## 202331034_NabilaRidhaAdman

In [10]:
import cv2

In [11]:
import matplotlib.pyplot as plt

In [15]:
import numpy as np

## 202331034_NabilaRidhaAdman

In [18]:
citra = cv2.imread('lemon.png')

In [20]:
cv2.imshow("citra asli", citra)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 202331034_NabilaRidhaAdman

In [23]:
print(citra.shape)
print(citra.dtype)

(1024, 1024, 3)
uint8


## 202331034_NabilaRidhaAdman

In [26]:
b = citra[:,:,0]
g = citra[:,:,1]
r = citra[:,:,2]

## 202331034_NabilaRidhaAdman

In [29]:
panjang = len(citra) #menghitung baris
lebar =  len(citra[0]) #menghitung kolom

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j] #merah=29,89% ; hijau=58,7% ; biru=11,41% 

citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("citra grayscale", citra_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
print(citra)

[[[26 24 22]
  [26 24 22]
  [26 24 22]
  ...
  [69 55 51]
  [70 58 53]
  [63 48 43]]

 [[26 24 22]
  [26 24 22]
  [26 24 22]
  ...
  [77 67 62]
  [79 63 58]
  [63 48 43]]

 [[26 24 22]
  [26 24 22]
  [26 24 22]
  ...
  [58 45 40]
  [64 52 47]
  [69 55 51]]

 ...

 [[17 16 15]
  [17 16 15]
  [17 16 15]
  ...
  [69 55 51]
  [50 41 38]
  [63 48 43]]

 [[17 16 15]
  [17 16 15]
  [17 16 15]
  ...
  [69 55 51]
  [58 45 40]
  [69 55 51]]

 [[17 16 15]
  [17 16 15]
  [17 16 15]
  ...
  [43 33 29]
  [63 48 43]
  [58 45 40]]]


In [31]:
print(citra_gray)

[[23 23 23 ... 55 57 48]
 [23 23 23 ... 66 63 48]
 [23 23 23 ... 44 51 55]
 ...
 [15 15 15 ... 55 41 48]
 [15 15 15 ... 55 44 55]
 [15 15 15 ... 32 48 44]]


## 202331034_NabilaRidhaAdman

In [33]:
panjang = len(citra) #menghitung baris
lebar =  len(citra[0]) #menghitung kolom

ambang = 90

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
            citra_biner[i,j] = 1 #putih
        else:
            citra_biner[i,j] = 0 #hitam

cv2.imshow("citra binary", citra_biner)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
print(citra_biner)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
